### ISSUE TITLE
Redux Form field values doesn't gets set

### ISSUE THREAD

**Issue by vaibhav-systango** [ilhammeidi/dandelion-starter#5]
Hi,

The redux form in this starterkit doesn't works as expected. Please check the issue and also if you want I can submit a PR for same

**Comment by vaibhav-systango** [comment]
@ilhammeidi

**Comment by ilhammeidi** [comment]
Yes you can submit the PR, Then i will check it

**Comment by vaibhav-systango** [comment]
yes but how can I push the code I don't have contributor access ? @ilhammeidi
