### ISSUE TITLE
Production Build  Issue

### ISSUE THREAD

**Issue by vaibhav-systango** [ilhammeidi/dandelion-starter#6]
npm run build when I ran for 12.6.x node version, static assets are not being served. Also when I tried build for node version 10.6.x  the build was not getting created and there was an error "Javascript heap out of memory"

**Comment by vaibhav-systango** [comment]
@ilhammeidi

**Comment by ilhammeidi** [comment]
Thanks for the reported issue. If you got the solution, please submit the PR
