### ISSUE TITLE
Manifest not being imported

### ISSUE THREAD

**Issue by vaibhav-systango** [ilhammeidi/dandelion-starter#7]
Hi there,
I have tried to add manifest.json in html page which is required for push notification but I am not able to get the manifest.json file in html file and on browser also I have checked in the application tab of inspector but didn't found it. Can you please help me with that I am using the dandelion pro template.

**Comment by ilhammeidi** [comment]
Hi, Could you please send me the invoice number and date purchase from envato/themeforest. (IVIPxxxxx) So we can help you further. Or you can raise the support via themeforest comment or our  profile message.
